# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T12:04:00+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field, RootModel


class Frequency(BaseModel):
    interval: int
    periodicity: str


class Item(BaseModel):
    frequency: Frequency
    quantity: int
    seller: str
    shippingAddressId: str
    sku: str


class ReindexrecurrenceRequest(BaseModel):
    frequency: Frequency


class UpdatepartialrecurrenceRequest(BaseModel):
    deliveryDay: int
    deliveryWeekday: str
    status: str


class UpdaterecurrenceRequest(BaseModel):
    deliveryDay: int
    deliveryWeekday: str
    email: str
    items: List[Item] = Field(..., description='')
    paymentAccountId: str


class UpdaterecurrencesettingsRequest(BaseModel):
    defaultSLA: str
    salesChannel: str


class SubscriptionsRecurrenceIdReindexPatchRequest(
    RootModel[List[ReindexrecurrenceRequest]]
):
    root: List[ReindexrecurrenceRequest] = Field(..., description='')


class AddrecurrenceitemRequest(BaseModel):
    frequency: Frequency
    quantity: int
    seller: str
    shippingAddressId: str
    sku: str


class SubscriptionsRecurrenceIdItemsPostRequest(
    RootModel[List[AddrecurrenceitemRequest]]
):
    root: List[AddrecurrenceitemRequest] = Field(..., description='')
